### ISSUE TITLE
no package "language-mocodo" in Atom Settings

### ISSUE THREAD

**Issue by laowantong** [ThomasGiro/atom-language-mocodo#1]
I failed to install the package in Atom (Preferences->Packages).

![capture d ecran 2016-11-20 16 16 52](https://cloud.githubusercontent.com/assets/3048819/20463889/1a47d99a-af3d-11e6-9f35-817cc079988e.png)

**Comment by Togimaro** [comment]
Yes sorry, it's in the Install section.
I have fix that in the README.
