### ISSUE TITLE
cardinalities are not highlighted

### ISSUE THREAD

**Issue by laowantong** [ThomasGiro/atom-language-mocodo#3]
Unfortunately, on my machine, there is no distinction between entities and cardinalities:

![capture d ecran 2016-11-20 17 00 28](https://cloud.githubusercontent.com/assets/3048819/20464163/e9c513b8-af42-11e6-9b50-b99abb1277b7.png)

For reference, your demonstration:

![mocodoatom](https://cloud.githubusercontent.com/assets/3048819/20464173/2996f362-af43-11e6-9078-e2717eb05f17.gif)

**Comment by Togimaro** [comment]
With what syntax theme?
I'll try to change the name for the entities

**Comment by laowantong** [comment]
Which theme? The default one, I suppose.
Anyway, the problem seems to occur in all default syntax themes.

**Comment by Togimaro** [comment]
I have change the naming convention can you update the package to try?

**Comment by laowantong** [comment]
That fixed the problem, thanks.
